### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hartalex** [hartalex/temperature_hub#4]
/server/api/data/slack.js:35
            reject(new Error('Error: ' + error + ' statusCode: ' + response.statusCode + ' body: ' + body));
                                                                            ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/root/temperature_hub/build/server/api/data/slack.js:35:77)
    at self.callback (/root/temperature_hub/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/root/temperature_hub/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

**Comment by hartalex** [comment]
Created a fix in 2908a0da3628a22b5da02d65b29d921c1559e04a
