### ISSUE TITLE
Error sensor/list

### ISSUE THREAD

**Issue by hartalex** [hartalex/temperature_hub#5]
error: GET /temp/current FetchError: request to https://hub.hartcode.com/temp/sensor/list failed, reason: getaddrinfo EAI_AGAIN hub.hartcode.com:443
    at ClientRequest.<anonymous> (/root/temperature_hub/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by hartalex** [comment]
One time Network issue
